### ISSUE TITLE
Move DEFAULT_PAGE_LIMIT to a config

### ISSUE THREAD

**Issue by NotEternal** [ref-finance/ref-sdk#1]
Here we use DEFAULT_PAGE_LIMIT as a constant:
https://github.com/ref-finance/ref-sdk/blob/e15fae08e53098e6839589dc5da976049315491a/src/pool.ts

It would be really helpful to add it as a config variable. So we can reduce amount of requests with a custom value, for example 500 | 1000 in limit.

**Comment by max-mainnet** [comment]
Thanks for this suggestion, we are to add more variables into configuration, such as node urls, as well as DEFAULT_PAGE_LIMIT you mentioned.

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/pull/7

**Comment by max-mainnet** [comment]
Hi @NotEternal ,  we add on option `perPage` for fetchAllPools function on 1.1.5 version https://github.com/ref-finance/ref-sdk/pull/7
