### ISSUE TITLE
Following the Swap Widget example, getting "Can't resolve 'fs'"

### ISSUE THREAD

**Issue by netpoe** [ref-finance/ref-sdk#10]
Followed the example of the Swap Widget as in the [README](https://github.com/ref-finance/ref-sdk#ref-swap-widget) file, but I get:

```
next-dev.js?3515:20 ./node_modules/@ref-finance/ref-sdk/dist/ref-sdk.esm.js:3:0
Module not found: Can't resolve 'fs'
```

In the browser console.

[See the implementation in my app here](https://github.com/aufacicenta/splitfund/blob/626218775cde59cb6b1220aa65bc6ca6a639350b/app/src/ui/splitfund/ref-swap-widget/RefSwapWidget.tsx).

package version: 

```
"@ref-finance/ref-sdk": "^1.1.5",
```

My guess is that the error [happens at `near.ts`](https://github.dev/ref-finance/ref-sdk/blob/5855bb13fea348b0ec77964066e18a9c2e8554b6/src/near.ts#L11): 

```
import fs from 'fs';
```

And then it gets [exported as a whole for both server and client](https://github.dev/ref-finance/ref-sdk/blob/5855bb13fea348b0ec77964066e18a9c2e8554b6/src/index.ts#L19) in `index.ts`: 

```
export * from './near';
```

Should we add logic whether to export `near.ts` for only server side?

**Comment by netpoe** [comment]
@max-mainnet any ideas what could be causing this error?
I know that outside the server environment, `fs` (file system) is not available, hence the error in the browser. But I assume the `SwapWidget` will not use `fs` in the client side?

**Comment by matricore** [comment]
+1

**Comment by max-mainnet** [comment]
Hi @matricore @netpoe thanks for reporting this one. I have noticed this pb these days, I think the quick fix on your side is to overrides the config in your dapp side, the following is what linear does to prevent this issue. They use webpack to package the app, I think it helps though just a temporary solution for it. 
![8681669893231_ pic](https://user-images.githubusercontent.com/50706666/205039051-3e94b736-fa23-4211-8e73-f4bfb725a5eb.jpg)

**Comment by max-mainnet** [comment]
> 
yes , that's the cause of this issue, sdk exports modules node env needs, so a conflict on web side.

**Comment by max-mainnet** [comment]
`I know that outside the server environment, fs (file system) is not available, hence the error in the browser. But I assume the SwapWidget will not use fs in the client side?`
yes this is the cause of the issue, we have decided to fix it in the future, listed in our todos now.

**Comment by netpoe** [comment]
@max-mainnet thanks for the reference. I was able to do it in NextJS 13 with:

```
module.exports = {
  webpack: (config, { isServer, webpack }) => {
    if (!isServer) {
      config.plugins.push(new webpack.NormalModuleReplacementPlugin(/^fs$/, "../package.json")); // resolve to any file, relative to the node_module directory
    }

    return config;
  },
};

```

**Comment by netpoe** [comment]
@max-mainnet following the discussion, I've found another issue: 

Now that the widget renders successfully, I'm setting the `defaultTokenList` prop to have only 2 tokens: 

```
return (
    <SwapWidget
      darkMode
      defaultTokenList={[defaultTokenInMetadata, defaultTokenOutMetadata]}
      className={clsx(styles["ref-swap-widget"], className)}
      onSwap={onSwap}
      onDisConnect={onDisConnect}
      width="100%"
      connection={{
        AccountId: accountId || "",
        isSignedIn: !!accountId,
      }}
      transactionState={{
        state: swapState,
        setState: setSwapState,
        tx,
        detail: "(success details show here)",
      }}
      enableSmartRouting
      onConnect={onConnect}
      defaultTokenIn={property.token.address}
      defaultTokenOut={property.contract.id}
    />
  );
```

Where `defaultTokenList={[defaultTokenInMetadata, defaultTokenOutMetadata]}` is: 

```
{
    "spec": "ft-1.0.0",
    "name": "Tether USD",
    "symbol": "USDT.e",
    "icon": "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Ccircle cx='16' cy='16' r='16' fill='%2326A17B'/%3E%3Cpath fill='%23FFF' d='M17.922 17.383v-.002c-.11.008-.677.042-1.942.042-1.01 0-1.721-.03-1.971-.042v.003c-3.888-.171-6.79-.848-6.79-1.658 0-.809 2.902-1.486 6.79-1.66v2.644c.254.018.982.061 1.988.061 1.207 0 1.812-.05 1.925-.06v-2.643c3.88.173 6.775.85 6.775 1.658 0 .81-2.895 1.485-6.775 1.657m0-3.59v-2.366h5.414V7.819H8.595v3.608h5.414v2.365c-4.4.202-7.709 1.074-7.709 2.118 0 1.044 3.309 1.915 7.709 2.118v7.582h3.913v-7.584c4.393-.202 7.694-1.073 7.694-2.116 0-1.043-3.301-1.914-7.694-2.117'/%3E%3C/g%3E%3C/svg%3E",
    "reference": null,
    "reference_hash": null,
    "decimals": 6,
    "id": "usdt.fakes.testnet"
}

{
    "spec": "ft-1.0.0",
    "name": "Splitfund.xyz Property 3",
    "symbol": "SF3",
    "reference": null,
    "reference_hash": null,
    "decimals": 6,
    "id": "splitfund-3-d7ce.factory.splitfund.testnet"
}
```

both valid NEP141 tokens. 

However, the widget won't display the latter: 

<img width="360" alt="Screen Shot 2022-12-01 at 11 05 04" src="https://user-images.githubusercontent.com/4053518/205115889-2803a28c-c256-42d9-9ab5-8ef8128b4956.png">

<img width="369" alt="Screen Shot 2022-12-01 at 11 04 56" src="https://user-images.githubusercontent.com/4053518/205115897-57df1dd1-e197-47b4-99f7-62e09c12c7a4.png">
