### ISSUE TITLE
SwapWidget defaultTokenList won't render expected NEP141 tokens

### ISSUE THREAD

**Issue by netpoe** [ref-finance/ref-sdk#11]
@max-mainnet following the discussion, I've found another issue: 

Now that the widget renders successfully, I'm setting the `defaultTokenList` prop to have only 2 tokens: 

```
return (
    <SwapWidget
      darkMode
      defaultTokenList={[defaultTokenInMetadata, defaultTokenOutMetadata]}
      className={clsx(styles["ref-swap-widget"], className)}
      onSwap={onSwap}
      onDisConnect={onDisConnect}
      width="100%"
      connection={{
        AccountId: accountId || "",
        isSignedIn: !!accountId,
      }}
      transactionState={{
        state: swapState,
        setState: setSwapState,
        tx,
        detail: "(success details show here)",
      }}
      enableSmartRouting
      onConnect={onConnect}
      defaultTokenIn={property.token.address}
      defaultTokenOut={property.contract.id}
    />
  );
```

Where `defaultTokenList={[defaultTokenInMetadata, defaultTokenOutMetadata]}` is: 

```
{
    "spec": "ft-1.0.0",
    "name": "Tether USD",
    "symbol": "USDT.e",
    "icon": "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Ccircle cx='16' cy='16' r='16' fill='%2326A17B'/%3E%3Cpath fill='%23FFF' d='M17.922 17.383v-.002c-.11.008-.677.042-1.942.042-1.01 0-1.721-.03-1.971-.042v.003c-3.888-.171-6.79-.848-6.79-1.658 0-.809 2.902-1.486 6.79-1.66v2.644c.254.018.982.061 1.988.061 1.207 0 1.812-.05 1.925-.06v-2.643c3.88.173 6.775.85 6.775 1.658 0 .81-2.895 1.485-6.775 1.657m0-3.59v-2.366h5.414V7.819H8.595v3.608h5.414v2.365c-4.4.202-7.709 1.074-7.709 2.118 0 1.044 3.309 1.915 7.709 2.118v7.582h3.913v-7.584c4.393-.202 7.694-1.073 7.694-2.116 0-1.043-3.301-1.914-7.694-2.117'/%3E%3C/g%3E%3C/svg%3E",
    "reference": null,
    "reference_hash": null,
    "decimals": 6,
    "id": "usdt.fakes.testnet"
}

{
    "spec": "ft-1.0.0",
    "name": "Splitfund.xyz Property 3",
    "symbol": "SF3",
    "reference": null,
    "reference_hash": null,
    "decimals": 6,
    "id": "splitfund-3-d7ce.factory.splitfund.testnet"
}
```

both valid NEP141 tokens. 

However, the widget won't display the latter: 

<img width="360" alt="Screen Shot 2022-12-01 at 11 05 04" src="https://user-images.githubusercontent.com/4053518/205115889-2803a28c-c256-42d9-9ab5-8ef8128b4956.png">

<img width="369" alt="Screen Shot 2022-12-01 at 11 04 56" src="https://user-images.githubusercontent.com/4053518/205115897-57df1dd1-e197-47b4-99f7-62e09c12c7a4.png">

---

My guess is that this line: https://github.dev/ref-finance/ref-sdk/blob/5855bb13fea348b0ec77964066e18a9c2e8554b6/src/swap-widget/state.tsx#L157 is returning `null` for the `parsedTokens` since one of the tokens I'm passing is not in the whitelist:

```
const getTokensList = async () => {
      const whiteList = await getGlobalWhitelist();
      const globalWhiteListTokens = (
        await getWhiteListTokensIndexer(whiteList)
      ).filter(token => !!token) as TokenMetadata[];

      const parsedTokens = globalWhiteListTokens.map(t => {
        return t.id === WRAP_NEAR_CONTRACT_ID
          ? {
              ...NEAR_META_DATA,
              id: t.id,
            }
          : t;
      });

      if (!defaultTokenList || defaultTokenList.length === 0) {
        setTokens(parsedTokens);
        setTokenLoading(false);
      } else {
        const newList = defaultTokenList
          .map(t => {
            return t.id === WRAP_NEAR_CONTRACT_ID
              ? {
                  ...NEAR_META_DATA,
                  id: t.id,
                }
              : t;
          })
          .filter(t => {
            // HERE, parsedTokens does not include my defaultTokenList because it was filtered above.
            return parsedTokens.findIndex(p => p.id === t.id) !== -1;
          });
```

**Comment by max-mainnet** [comment]
`since one of the tokens I'm passing is not in the whitelist:`
Hi @netpoe , this is the cause of it, currently we just support tokens in the whitelist to be the candidate tokens, let me talk about it with dev team and pm about how to deal with it, will give it back to you soon.

**Comment by max-mainnet** [comment]
@netpoe splitfund-3-d7ce.factory.splitfund.testnet  is now added to ref white list, please check again.
Note: For mainnet, you need to contact Ref PM to apply your mainnet token into ref white list.

**Comment by netpoe** [comment]
> @netpoe splitfund-3-d7ce.factory.splitfund.testnet is now added to ref white list, please check again. Note: For mainnet, you need to contact Ref PM to apply your mainnet token into ref white list.

Thanks. However, I don't think this "ask for whitelisting" procedure is sustainable, since the dApp I'm working on generates new NEP141s on demand and often...

I think I'm going to use the `swap` function for now and display my own widget for now.
