### ISSUE TITLE
ftGetTokensMetadata didn't work as expected

### ISSUE THREAD

**Issue by matricore** [ref-finance/ref-sdk#12]
In the documentation, it says we can pull metadata of all available tokens with this method but i couldn't find a way  to do this. I tried to query with an empty array it returns-out an empty objects, I tried to fill-out the array with contract address it returns error below. 

`TypeError: Cannot read properties of undefined (reading 'ref.fakes.testnet')`

**Comment by max-mainnet** [comment]
Hi @matricore ,
`    ftGetTokensMetadata(["ref.fakes.testnet", "wrap.testnet"], {}).then((res) => {
      console.log({
        res,
      });
    });`
Please use it in this way, sorry for that the document is not updated in time.

**Comment by matricore** [comment]
Hi @max-mainnet ,
Yes i solved that in the same way while trying, thank you. 
So, how can i get all available tokens? Because documentation said that `You can use 'ftGetTokensMetadata' function to get all available tokens, and list them in the token selector to allow users to select their trading pair`
I think i must filled-out the array manually :(

**Comment by max-mainnet** [comment]
the ftGetTokensMetadata function is to get all metadata by input array; I think you should call getGlobalWhitelist function to get all ref whitelist token ids and the input these ids to ftGetTokensMetadata to get those metadata. Does it help ?

**Comment by matricore** [comment]
yes it works like a charm. I think it should be added to the documentation. i can help you dealing with this

**Comment by max-mainnet** [comment]
What if I set the array as an option, as well as second parameter, then set global whitelist as the default array if not token list input to call ftGetTokensMetadata ?

**Comment by max-mainnet** [comment]
Then no need to modify the document and make the function more powerful ?

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/pull/13

**Comment by matricore** [comment]
> 

great idea. if you do that nobody needs documentation update

**Comment by matricore** [comment]
resolved

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/pull/14
ftGetTokensMetadata function updated
