### ISSUE TITLE
why instantSwap return an array of transaction ?

### ISSUE THREAD

**Issue by thanhnguyennguyen** [ref-finance/ref-sdk#19]
why instantSwap return an array of transaction ? 
even smartRouting is enable, it should be only one transaction with multiple actions I think

```javascript
const transactionsRef: Transaction[] = await instantSwap({
  tokenIn,
  tokenOut,
  amountIn: '1',
  swapTodos,
  slippageTolerance = 0.01,
  AccountId: 'your-account-id.testnet',
  referralId: 'ref-fee.testnet'
});
```

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/blob/7fe4cef5ce142896caccdb8c02e188e5696559f4/src/v1-swap/instantSwap.ts#L34-L71

**Comment by max-mainnet** [comment]
> https://github.com/ref-finance/ref-sdk/blob/7fe4cef5ce142896caccdb8c02e188e5696559f4/src/v1-swap/instantSwap.ts#L34-L71

for instant swap, it is a transaction with multi actions, but we would help user to register the token out, and wrap near when it is the token in, so generally we return an array of transactions.

**Comment by thanhnguyennguyen** [comment]
thanks @max-mainnet

**Comment by max-mainnet** [comment]
What do you mean to ignore such case ?  I guess the reason you put same token in and token out was to "find any route to earn wrap.near" ?  We currently won't take such case into account on top of our swap algorithm. Or if you mean to how to generate transactions, you could refer to https://github.com/ref-finance/ref-sdk/blob/main/src/v1-swap/instantSwap.ts#L104-L115,  just put token in and token out with wrap.near.

**Comment by thanhnguyennguyen** [comment]
I wonder
- What is the flag/option to trigger deposit NEAR action in case my tokenIn is Native NEAR ?
- What is the flag/option to trigger unwrap to Native Near in case my token Out is wrapNear ?

**Comment by max-mainnet** [comment]
case swap-widget: sdk will automatically deposit NEAR, and unwrap to Native NEAR;
case v1-swap: we don't force to add above actions in to instant swap, you could refer to nearDepositTransaction or nearWithdrawTransaction for you to customize your transactions; 
case dcl-swap: we currently don't support Native NEAR as the token in, but for token out as wrap.near, dcl contract side will unwrap to Native NEAR and finally you will get Native NEAR.

**Comment by thanhnguyennguyen** [comment]
thank you
