### ISSUE TITLE
Error in all pools fetching

### ISSUE THREAD

**Issue by NotEternal** [ref-finance/ref-sdk#2]
There is a syntax error in formatting when fetching all pools:

[The problem line in pools.ts](https://github.com/ref-finance/ref-sdk/blob/e15fae08e53098e6839589dc5da976049315491a/src/pool.ts#L70)

![error-place](https://user-images.githubusercontent.com/61930014/193281695-196f6945-01fe-4b45-901a-b3451be9395e.png)

Error:
`TypeError: Cannot read properties of undefined (reading 'pool_kind')`

**Comment by NotEternal** [comment]
@max-mainnet 
1. I install a SDK package and start using -> mport all code from the package and run `sdk.fetchAllPools()`
2. I call `getRefPools(1)` before other Promises -> add some logs in a function -> built code with a build command (correct it to save only a `esm` format). Run with `node dist/ref-sdk.esm.js`.

> getRefPools() works fine

**Comment by max-mainnet** [comment]
>  add some logs in a function
Seems like it didn't get any pools from rpc.  Could you please post the function you have modified ?

**Comment by NotEternal** [comment]
> 

`fetchAllPools()`

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/commit/960f1a8f07a96a9278e33c404212b0d2b5233a4b

**Comment by max-mainnet** [comment]
fixed in new version 1.0.2
