### ISSUE TITLE
Will ftGetTokenMetadata fetch data about any NEP141 token, or just the tokens listed in app.ref.finance?

### ISSUE THREAD

**Issue by netpoe** [ref-finance/ref-sdk#8]
This leads me to another question regarding the Swap widget and its use cases: _Swapping stablecoins for your project's token_.

In order to make this work, how to display "my project's token"?

This is not a bug report, just a noob question. Thanks.

**Comment by max-mainnet** [comment]
Hi @netpoe , ftGetTokenMetadata could fetch data any NEP141 token, in fact it views token contract on ft_metadata method.  The only thing you need to do is to input token address.
---
There is an option called `defaultTokenList` (not showing on README.md, let me update the doc), the widget will show 
the intersection of `defaultTokenList` and `Ref global whitelist tokens + user whitelist tokens`, which shows on token list in the widget. 

So for `Swapping stablecoins for your project's token.`,   what I would do is to collect all stablecoins' address and then set   their metadata into `defaultTokenList` option.

**Comment by max-mainnet** [comment]
https://github.com/ref-finance/ref-sdk/pull/13
Document about  defaultTokenList updated in this PR
